extends:
  - "airbnb-base"
  - "prettier"

plugins:
  - "prettier"

rules:
  no-console: ["error", { allow: ["info", "error", "warn"] }]
  no-plusplus: ["off"]

  import/no-extraneous-dependencies: ["off"]
  prettier/prettier: ["error"]

overrides:
  - files:
      - "__mocks__/*"
      - "jest.setup.js"
      - "*.test.js"

    env:
      jest: true
